FROM node:16 as base
# create app directoory
WORKDIR /home/app
COPY package*.json ./

RUN npm install
#RUN npm i -D typescript ts-node @types/node
# If you are building your code for production
RUN npm ci --only=production && npm cache clean --force
# Bundle app source
COPY . .
#CMD [ "ts-node", "index.js" ]

FROM base as production
ENV NODE_PATH=./
RUN npm run build
